config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tweets#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text,
    against: {
    username: 'A',
    id: 'B',
    }    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:limit] = 10
    include Pagy::Backend
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @pagy, @tweets = pagy(Tweet.all)

   if params[:query_text].present?
    @tweets = @tweets.search_full_text(params[:query_text])
    
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_path, status: :see_other, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clonetwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Description:</strong>
    <%= tweet.description %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= tweet.username %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1 class="title">Editing Tweet</h1>

<div class="form-container">
  <%= render "form", tweet: @tweet %>
</div>

<div class="actions">
  <%= link_to "Show this Tweet", @tweet, class: "btn" %>
  <%= link_to "Back to Tweets", tweets_path, class: "btn" %>
</div>

app/views/tweets/index.html.erb
<p class="notice"><%= notice %></p>

<h1 class="title">
  <%= link_to "Tweets", tweets_path(page: 1) %>
</h1>

<div class="header">
  <div class="new-tweet">
    <%= link_to "New Tweet", new_tweet_path, class: "btn-new-tweet" %>
  </div>

  <div class="search">
    <%= form_with url: tweets_path, method: :get, class: "search-form" do |form| %>
      <%= form.text_field :query_text, placeholder: 'Search "Eastern" Tweet', value: params[:query_text], class: "search-input" %>
    <% end %>
  </div>
</div>

<div id="tweets" class="tweets-list">
  <% @tweets.each do |tweet| %>
    <div class="tweet-item">
      <%= render tweet %>
      <p>
        <%= link_to "Show this tweet", tweet, class: "btn-show" %>
      </p>
    </div>
  <% end %>
</div>

<div class="pagination">
  <%=raw pagy_nav(@pagy)%>
</div>

app/views/tweets/new.html.erb
<h1 class="title">New Tweets</h1>

<div class="form-container">
  <%= render "form", tweet: @tweet %>
</div>

<div class="actions">
  <%= link_to "Show this Tweet", @tweet, class: "btn" %>
  <%= link_to "Back to Tweets", tweets_path, class: "btn" %>
</div>

app/views/tweets/show.html.erb
<p class="notice"><%= notice %></p>

<div class="tweet-container">
  <%= render @tweet %>
</div>

<div class="actions">
  <%= link_to "Edit this Tweet", edit_tweet_path(@tweet), class: "btn-edit" %>
  <%= link_to "Back to Tweets", tweets_path, class: "btn-back" %>
  <%= button_to "Delete this Tweet", @tweet, method: :delete, class: "btn-delete" %>
</div>